import { useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { AcademicDetailsFields } from "../../components/profile/AcademicDetailsFields";
import { Button } from "../../components/ui/Button";
import { useAuth } from "../../context/AuthContext";
import { supabase } from "../../lib/supabase";
import type { AcademicDetailsInput } from "../../services/profiles";

const emptyDetails:AcademicDetailsInput={university:"",major:"",catalog_year:null,expected_graduation_term:null,graduation_year:null};
export function OnboardingPage(){const {user}=useAuth();const navigate=useNavigate();const [fullName,setFullName]=useState(""),[details,setDetails]=useState<AcademicDetailsInput>(emptyDetails),[error,setError]=useState(""),[saving,setSaving]=useState(false);useEffect(()=>{if(!user)return;supabase.from("profiles").select("full_name,university,major,graduation_year,catalog_year,expected_graduation_term,onboarding_completed").eq("id",user.id).single().then(({data,error:loadError})=>{if(loadError){setError(loadError.message);return}if(!data)return;if(data.onboarding_completed)navigate("/dashboard",{replace:true});setFullName(data.full_name);setDetails({university:data.university,major:data.major,graduation_year:data.graduation_year,catalog_year:data.catalog_year,expected_graduation_term:data.expected_graduation_term})})},[user,navigate]);async function submit(event:FormEvent){event.preventDefault();if(!user)return;setSaving(true);setError("");const {error:saveError}=await supabase.from("profiles").upsert({id:user.id,email:user.email,full_name:fullName,...details,onboarding_completed:true,updated_at:new Date().toISOString()});setSaving(false);if(saveError)setError(saveError.message);else navigate("/dashboard",{replace:true})}return <main className="auth-page"><div className="auth-card"><p className="eyebrow">Basic academic setup</p><h1>Make Pathly yours.</h1><p>Provide the details you know. You can update them later in Settings.</p><form onSubmit={submit}><label>Full name<input value={fullName} onChange={event=>setFullName(event.target.value)} required/></label><AcademicDetailsFields value={details} onChange={setDetails}/>{error&&<p className="form-message" role="alert">{error}</p>}<Button type="submit" disabled={saving}>{saving?"Saving…":"Save and continue"}</Button></form></div></main>}
