import { useNavigate } from "react-router-dom";
import { FocusItem } from "../../components/dashboard/FocusItem";
import { PageHeader } from "../../components/layout/PageHeader";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { Icon } from "../../components/ui/Icon";
import { useFocusTasks } from "../../hooks/useFocusTasks";
import { dashboardExam, demoStudent, upcomingSchedule } from "../../data/appData";
export function DashboardPage() { const {tasks,completed,toggle}=useFocusTasks(); const navigate=useNavigate(); return <><PageHeader title={`Good morning, ${demoStudent.firstName}.`}/><main className="page dashboard"><div className="welcome"><div><p className="calm-line">Let’s make today feel a little lighter.</p><h2>Here’s what matters today.</h2></div><div className="weather"><Icon name="sun" size={22}/><span>52°</span><small>Clear & quiet</small></div></div><div className="dashboard-grid"><Card className="focus-card"><div className="card-heading"><div><p className="eyebrow">Today’s focus</p><h3>Three things is enough.</h3></div><Badge>{completed.length}/3 complete</Badge></div><div className="focus-list">{tasks.map((task,index)=><FocusItem key={task.id} task={task} number={index+1} completed={completed.includes(task.id)} onToggle={()=>toggle(task.id)}/>)}</div><div className="focus-footer"><span>Everything else can wait.</span><div className="mini-progress"><i style={{width:`${completed.length/tasks.length*100}%`}}/></div></div></Card><aside className="side-stack"><Card className="exam-card"><div className="exam-icon"><Icon name="file"/></div><p className="eyebrow">Upcoming exam</p><h3>{dashboardExam.title}</h3><p>{dashboardExam.date}</p><div className="exam-footer"><Badge tone="gold">{dashboardExam.countdown}</Badge><button onClick={()=>navigate("/study")} className="text-button">Review plan <Icon name="arrow" size={16}/></button></div></Card><Card className="study-card"><p className="eyebrow">Study session</p><h3>Ready when you are.</h3><p>A 25-minute focus block for Programming Assignment 4.</p><Button onClick={()=>navigate("/companion")}><Icon name="play" size={15}/> Start focus</Button></Card></aside></div><div className="lower-grid"><Card><div className="card-heading"><div><p className="eyebrow">Coming up</p><h3>Gentle heads-up</h3></div><button onClick={()=>navigate("/calendar")} className="text-button">View calendar <Icon name="arrow" size={16}/></button></div><div className="schedule-list">{upcomingSchedule.map(item=><div key={item.time}><b>{item.time}</b><span className={`event-dot ${item.tone}`}/><p><strong>{item.title}</strong><small>{item.location}</small></p></div>)}</div></Card><ReflectionCard/></div></main></>; }
function ReflectionCard() { return <Card className="reflection"><p className="eyebrow">Daily reflection</p><h3>How are you feeling today?</h3><div className="moods">{["😣","😕","🙂","😊","🌿"].map((mood,index)=><button key={mood} className={index===2?"selected":""} aria-label={`Mood ${mood}`}>{mood}</button>)}</div><textarea aria-label="Reflection note" placeholder="A win from CSCE 1030, or a note for tomorrow? (optional)"/><Button>Save reflection</Button></Card>; }
