import { useNavigate } from "react-router-dom";
import { FocusItem } from "../../components/dashboard/FocusItem";
import { PageHeader } from "../../components/layout/PageHeader";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { Icon } from "../../components/ui/Icon";
import { useFocusTasks } from "../../hooks/useFocusTasks";
export function DashboardPage() { const {tasks,completed,toggle}=useFocusTasks(); const navigate=useNavigate(); return <><PageHeader title="Good morning, Alex."/><main className="page dashboard"><div className="welcome"><div><p className="calm-line">Let’s make today feel a little lighter.</p><h2>Here’s what matters today.</h2></div><div className="weather"><Icon name="sun" size={22}/><span>52°</span><small>Clear & quiet</small></div></div><div className="dashboard-grid"><Card className="focus-card"><div className="card-heading"><div><p className="eyebrow">Today’s focus</p><h3>Three things is enough.</h3></div><Badge>{completed.length}/3 complete</Badge></div><div className="focus-list">{tasks.map((task,index)=><FocusItem key={task.id} task={task} number={index+1} completed={completed.includes(task.id)} onToggle={()=>toggle(task.id)}/>)}</div><div className="focus-footer"><span>Everything else can wait.</span><div className="mini-progress"><i style={{width:`${completed.length/tasks.length*100}%`}}/></div></div></Card><aside className="side-stack"><Card className="exam-card"><div className="exam-icon"><Icon name="file"/></div><p className="eyebrow">Upcoming exam</p><h3>Chemistry Midterm</h3><p>Friday, Oct 17 · 10:00 AM</p><div className="exam-footer"><Badge tone="gold">3 days away</Badge><button onClick={()=>navigate("/study")} className="text-button">Review plan <Icon name="arrow" size={16}/></button></div></Card><Card className="study-card"><p className="eyebrow">Study session</p><h3>Ready when you are.</h3><p>A 25-minute focus block for your lab report.</p><Button onClick={()=>navigate("/companion")}><Icon name="play" size={15}/> Start focus</Button></Card></aside></div><div className="lower-grid"><Card><div className="card-heading"><div><p className="eyebrow">Coming up</p><h3>Gentle heads-up</h3></div><button onClick={()=>navigate("/calendar")} className="text-button">View calendar <Icon name="arrow" size={16}/></button></div><div className="schedule-list">{[["11:00","blue","Calculus II","Science Hall 204"],["3:30","sage","Library shift","West Wing · 3 hours"],["7:00","gold","Study block","Biology Lab Report"]].map(([time,tone,title,location])=><div key={time}><b>{time}</b><span className={`event-dot ${tone}`}/><p><strong>{title}</strong><small>{location}</small></p></div>)}</div></Card><ReflectionCard/></div></main></>; }
function ReflectionCard() { return <Card className="reflection"><p className="eyebrow">Daily reflection</p><h3>How are you feeling today?</h3><div className="moods">{["😣","😕","🙂","😊","🌿"].map((mood,index)=><button key={mood} className={index===2?"selected":""} aria-label={`Mood ${mood}`}>{mood}</button>)}</div><textarea aria-label="Reflection note" placeholder="Anything on your mind? (optional)"/><Button>Save reflection</Button></Card>; }
