import assert from "node:assert/strict"
import test from "node:test"
import { calculateDegreeProgress } from "./degreeProgress.ts"
import type { CompletedCourse, DegreeProgram, RequirementGroup, UserDegreePlan } from "../types/degreePlanning.ts"

const program={id:"program",university:"UNT",degree:"BS",major:"Computer Science",catalog_year:2025,total_credits_required:120,source_url:"https://example.test",source_title:"Official",verified_at:"2026-01-01"} satisfies DegreeProgram
const choice={id:"breadth",program_id:"program",name:"CSCE Breadth Choices",description:null,requirement_type:"minimum_credits",matching_strategy:"degree_audit_review",minimum_credits:6,sort_order:1,requirement_course_options:[]} satisfies RequirementGroup
const course=(code:string,status:"completed"|"in_progress",id=code):CompletedCourse=>({id,user_id:"user",course_code:code,course_title:"Course",credit_hours:3,term:null,year:null,source:"transcript",status,source_upload_id:null,created_at:"",updated_at:""})
const audit=(applications:Array<{id:string;code:string;credits:number}>):UserDegreePlan=>({id:"plan",source_upload_id:"upload",university:"UNT",major:"Computer Science",catalog_year:2025,total_credits_required:120,total_credits_completed:3,requirement_source:"degree_audit",status:"active",confirmed_at:"2026-01-01",user_degree_requirement_groups:[{id:"audit-group",requirement_label:"CSCE Breadth Choices",status:"in_progress",credits_required:6,credits_completed:3,credits_remaining:3,details:null,sort_order:1,user_degree_requirements:applications.map(item=>({id:item.id,requirement_type:"course",course_code:item.code,requirement_text:item.code,status:"in_progress",credits_applied:item.credits,application_source:"degree_audit"}))}]})

test("completed audit application counts and in-progress stays separate",()=>{const result=calculateDegreeProgress(program,[choice],[course("CSCE 4000","completed"),course("CSCE 4010","in_progress")],audit([{id:"a",code:"CSCE 4000",credits:3},{id:"b",code:"CSCE 4010",credits:3}])).groupProgress[0];assert.equal(result.completedCredits,3);assert.equal(result.inProgressCredits,3);assert.equal(result.unresolvedCredits,0)})
test("unmapped completed course never satisfies an audit-reviewed choice",()=>{const result=calculateDegreeProgress(program,[choice],[course("CSCE 4000","completed")],audit([])).groupProgress[0];assert.equal(result.completedCredits,0);assert.equal(result.requiresReview,true)})
test("duplicate transcript rows and duplicate mappings count once",()=>{const result=calculateDegreeProgress(program,[choice],[course("CSCE 4000","in_progress","one"),course("CSCE 4000","completed","two")],audit([{id:"a",code:"CSCE 4000",credits:3},{id:"b",code:"CSCE 4000",credits:3}])).groupProgress[0];assert.equal(result.completedCredits,3);assert.equal(result.inProgressCredits,0)})
test("missing or over-applied coursework is marked for review",()=>{const result=calculateDegreeProgress(program,[choice],[course("CSCE 4000","completed")],audit([{id:"a",code:"CSCE 4000",credits:6},{id:"b",code:"CSCE 4999",credits:3}])).groupProgress[0];assert.equal(result.completedCredits,0);assert.deepEqual(result.needsReview,["CSCE 4000","CSCE 4999"])})
test("the same explicitly audited course may appear across groups without inflating degree totals",()=>{const second={...choice,id:"option",name:"CSCE Option Courses"};const plan=audit([{id:"a",code:"CSCE 4000",credits:3}]);plan.user_degree_requirement_groups.push({...plan.user_degree_requirement_groups[0],id:"option-audit",requirement_label:"CSCE Option Courses",user_degree_requirements:[{...plan.user_degree_requirement_groups[0].user_degree_requirements[0],id:"b"}]});const result=calculateDegreeProgress(program,[choice,second],[course("CSCE 4000","completed")],plan);assert.equal(result.completedCredits,3);assert.equal(result.groupProgress[0].completedCredits,3);assert.equal(result.groupProgress[1].completedCredits,3)})
