import { useMemo, useState } from "react";

type Page = "home" | "study" | "calendar" | "degree" | "companion" | "upload" | "profile";
type IconName = "home" | "book" | "calendar" | "chart" | "sparkle" | "upload" | "settings" | "arrow" | "play" | "plus" | "clock" | "check" | "file" | "sun" | "moon" | "smile" | "send" | "bell";

const Icon = ({ name, size = 20 }: { name: IconName; size?: number }) => {
  const paths: Record<IconName, React.ReactNode> = {
    home: <><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-6h6v6"/></>,
    book: <><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"/><path d="M4 19a2.5 2.5 0 0 1 2.5-2.5H20"/></>,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 3 2 5-7"/></>,
    sparkle: <><path d="m12 3-1.4 5.6L5 10l5.6 1.4L12 17l1.4-5.6L19 10l-5.6-1.4L12 3Z"/><path d="m19 16-.6 2.4L16 19l2.4.6L19 22l.6-2.4L22 19l-2.4-.6L19 16Z"/></>,
    upload: <><path d="M12 16V3M7 8l5-5 5 5"/><path d="M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.2 2.2-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.2h-3.2v-.2a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1L6.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.5-1H5v-3.2h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 2.2-2.2.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V4h3.2v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 2.2 2.2-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.1V14h-.1a1.7 1.7 0 0 0-1.5 1Z"/></>,
    arrow: <path d="M5 12h14M13 6l6 6-6 6"/>, play: <path d="m8 5 11 7-11 7V5Z"/>, plus: <path d="M12 5v14M5 12h14"/>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, check: <path d="m5 12 4 4L19 6"/>,
    file: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>,
    sun: <><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></>,
    moon: <path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/>, smile: <><circle cx="12" cy="12" r="9"/><path d="M8 14s1.3 2 4 2 4-2 4-2M9 9h.01M15 9h.01"/></>,
    send: <path d="m21 3-7.5 18-3.8-7.7L2 9.5 21 3Z"/>, bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 22h4"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
};

const Button = ({ children, onClick, variant = "primary", className = "" }: { children: React.ReactNode; onClick?: () => void; variant?: "primary" | "secondary" | "quiet"; className?: string }) => <button onClick={onClick} className={`btn btn-${variant} ${className}`}>{children}</button>;
const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`card ${className}`}>{children}</section>;
const Badge = ({ children, tone = "green" }: { children: React.ReactNode; tone?: "green" | "gold" | "rose" | "gray" }) => <span className={`badge badge-${tone}`}>{children}</span>;

const courses = [
  { code: "BIO 214", name: "Cell Biology", color: "sage", next: "Lab report due today" },
  { code: "MATH 221", name: "Calculus II", color: "gold", next: "Problem set · Friday" },
  { code: "HIST 137", name: "Modern World History", color: "clay", next: "Reading · Thursday" },
];

function Logo() { return <div className="brand"><span className="leaf">✦</span><span>Pathly</span></div>; }

function Sidebar({ page, setPage }: { page: Page; setPage: (p: Page) => void }) {
  const nav: { id: Page; label: string; icon: IconName }[] = [
    { id: "home", label: "Today", icon: "home" }, { id: "study", label: "Study hub", icon: "book" }, { id: "calendar", label: "Calendar", icon: "calendar" }, { id: "degree", label: "Degree plan", icon: "chart" }, { id: "companion", label: "Companion", icon: "sparkle" }, { id: "upload", label: "Uploads", icon: "upload" },
  ];
  return <aside className="sidebar"><Logo/><nav aria-label="Main navigation">{nav.map(item => <button key={item.id} onClick={() => setPage(item.id)} className={`nav-item ${page === item.id ? "active" : ""}`}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><div className="sidebar-bottom"><button onClick={() => setPage("profile")} className={`nav-item ${page === "profile" ? "active" : ""}`}><Icon name="settings"/><span>Settings</span></button><div className="user-card"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><small>Biology, Class of ’27</small></div></div></div></aside>;
}

function Topbar({ title, onUpload }: { title: string; onUpload: () => void }) { return <header className="topbar"><div><p className="eyebrow">Tuesday, October 14</p><h1>{title}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Icon name="bell"/></button><Button variant="secondary" onClick={onUpload}><Icon name="upload" size={17}/> Add material</Button></div></header>; }

function FocusItem({ number, title, detail, time, done, toggle }: { number: number; title: string; detail: string; time: string; done: boolean; toggle: () => void }) { return <button onClick={toggle} className={`focus-item ${done ? "done" : ""}`}><span className="focus-number">{done ? <Icon name="check" size={16}/> : `0${number}`}</span><span className="focus-copy"><strong>{title}</strong><small>{detail}</small></span><span className="focus-time"><Icon name="clock" size={15}/>{time}</span></button>; }

function Dashboard({ setPage }: { setPage: (p: Page) => void }) {
  const [done, setDone] = useState([false, false, false]);
  const completed = done.filter(Boolean).length;
  return <><Topbar title="Good morning, Alex." onUpload={() => setPage("upload")}/><main className="page dashboard"><div className="welcome"><div><p className="calm-line">Let’s make today feel a little lighter.</p><h2>Here’s what matters today.</h2></div><div className="weather"><Icon name="sun" size={22}/><span>52°</span><small>Clear & quiet</small></div></div><div className="dashboard-grid"><Card className="focus-card"><div className="card-heading"><div><p className="eyebrow">Today’s focus</p><h3>Three things is enough.</h3></div><Badge>{completed}/3 complete</Badge></div><div className="focus-list"><FocusItem number={1} title="Biology Lab Report" detail="Results + discussion section" time="90 min" done={done[0]} toggle={() => setDone(d => d.map((x, i) => i === 0 ? !x : x))}/><FocusItem number={2} title="Review Photosynthesis" detail="Cell Biology · Lecture 8" time="45 min" done={done[1]} toggle={() => setDone(d => d.map((x, i) => i === 1 ? !x : x))}/><FocusItem number={3} title="Read History Chapter 6" detail="Modern World History" time="30 min" done={done[2]} toggle={() => setDone(d => d.map((x, i) => i === 2 ? !x : x))}/></div><div className="focus-footer"><span>Everything else can wait.</span><div className="mini-progress"><i style={{ width: `${completed / 3 * 100}%` }}/></div></div></Card><aside className="side-stack"><Card className="exam-card"><div className="exam-icon"><Icon name="file"/></div><p className="eyebrow">Upcoming exam</p><h3>Chemistry Midterm</h3><p>Friday, Oct 17 · 10:00 AM</p><div className="exam-footer"><Badge tone="gold">3 days away</Badge><button onClick={() => setPage("study")} className="text-button">Review plan <Icon name="arrow" size={16}/></button></div></Card><Card className="study-card"><p className="eyebrow">Study session</p><h3>Ready when you are.</h3><p>A 25-minute focus block for your lab report.</p><Button onClick={() => setPage("companion")}><Icon name="play" size={15}/> Start focus</Button></Card></aside></div><div className="lower-grid"><Card><div className="card-heading"><div><p className="eyebrow">Coming up</p><h3>Gentle heads-up</h3></div><button onClick={() => setPage("calendar")} className="text-button">View calendar <Icon name="arrow" size={16}/></button></div><div className="schedule-list"><div><b>11:00</b><span className="event-dot blue"/><p><strong>Calculus II</strong><small>Science Hall 204</small></p></div><div><b>3:30</b><span className="event-dot sage"/><p><strong>Library shift</strong><small>West Wing · 3 hours</small></p></div><div><b>7:00</b><span className="event-dot gold"/><p><strong>Study block</strong><small>Biology Lab Report</small></p></div></div></Card><Reflection/></div></main></>;
}

function Reflection() { const [saved, setSaved] = useState(false); const [mood, setMood] = useState("🙂"); return <Card className="reflection"><p className="eyebrow">Daily reflection</p><h3>How are you feeling today?</h3><div className="moods">{["😣", "😕", "🙂", "😊", "🌿"].map(m => <button key={m} className={mood === m ? "selected" : ""} onClick={() => setMood(m)} aria-label={`Mood ${m}`}>{m}</button>)}</div><textarea aria-label="Reflection note" placeholder="Anything on your mind? (optional)"/><Button variant={saved ? "secondary" : "primary"} onClick={() => setSaved(true)}>{saved ? "Reflection saved" : "Save reflection"}</Button></Card>; }

function StudyHub({ setPage }: { setPage: (p: Page) => void }) { return <><Topbar title="Study hub" onUpload={() => setPage("upload")}/><main className="page"><div className="intro-row"><div><h2>Learn in the way that helps it stick.</h2><p>Everything from your courses, made easier to return to.</p></div><Button onClick={() => setPage("upload")}><Icon name="plus" size={17}/> Upload lecture</Button></div><div className="course-grid">{courses.map(c => <Card key={c.code} className="course-card"><div className={`course-mark ${c.color}`}>{c.code}</div><div><Badge tone="gray">{c.code}</Badge><h3>{c.name}</h3><p>{c.next}</p></div><button className="text-button">Open course <Icon name="arrow" size={16}/></button></Card>)}</div><section className="materials"><div className="section-title"><div><p className="eyebrow">Recently added</p><h2>Your study materials</h2></div><button className="text-button">See all <Icon name="arrow" size={16}/></button></div><div className="material-grid">{[["Photosynthesis: Light Reactions", "Lecture summary", "12 min read", "sage"], ["Cellular Respiration", "24 flashcards", "Practice set", "gold"], ["Genetics Review", "Practice quiz", "10 questions", "clay"]].map(([title,type,detail,tone]) => <Card key={title} className="material-card"><div className={`file-icon ${tone}`}><Icon name="file"/></div><div><Badge tone="gray">{type}</Badge><h3>{title}</h3><p>{detail}</p></div><button className="round-arrow"><Icon name="arrow" size={17}/></button></Card>)}</div></section></main></> }

function CalendarPage({ setPage }: { setPage: (p: Page) => void }) { const days = ["Mon 13","Tue 14","Wed 15","Thu 16","Fri 17","Sat 18","Sun 19"]; return <><Topbar title="Your week" onUpload={() => setPage("upload")}/><main className="page"><div className="calendar-toolbar"><div><h2>A week with room to breathe.</h2><p>October 13 – 19, 2026</p></div><div><Button variant="secondary">Today</Button> <Button variant="quiet">‹ &nbsp; ›</Button></div></div><Card className="week-card"><div className="week-grid">{days.map((d,i) => <div className={`day ${i === 1 ? "today" : ""}`} key={d}><b>{d}</b><div className="time-label">9 AM</div>{i===0 && <div className="calendar-event sage">BIO 214 Lab<br/><small>9:00–11:00</small></div>}{i===1 && <><div className="calendar-event blue">Calculus II<br/><small>11:00–12:15</small></div><div className="calendar-event gold offset">Library shift<br/><small>3:30–6:30</small></div></>}{i===2 && <div className="calendar-event clay">History seminar<br/><small>1:00–2:15</small></div>}{i===4 && <div className="calendar-event rose">Chemistry midterm<br/><small>10:00–12:00</small></div>}</div>)}</div></Card><div className="calendar-bottom"><Card><p className="eyebrow">This week</p><h3>5 commitments, 3 focus blocks</h3><p>You have a little more room Wednesday evening. It could be a gentle catch-up window.</p></Card><Card><p className="eyebrow">Protected time</p><h3>Keep Sunday open</h3><p>A quiet reset is already on your calendar. We’ll protect it.</p></Card></div></main></> }

function DegreePage({ setPage }: { setPage: (p: Page) => void }) { return <><Topbar title="Degree plan" onUpload={() => setPage("upload")}/><main className="page"><div className="intro-row"><div><h2>You’re making steady progress.</h2><p>Your degree is a long path. You don’t have to hold it all in your head.</p></div><Button variant="secondary">Edit plan</Button></div><Card className="degree-hero"><div className="degree-ring"><strong>58%</strong><span>complete</span></div><div><p className="eyebrow">B.S. Biology · 2027</p><h2>72 of 124 credits completed</h2><p>You’re on track to graduate in Spring 2027.</p><div className="wide-progress"><i/></div></div></Card><div className="degree-grid"><Card><p className="eyebrow">Requirements</p><h3>What’s left</h3>{[["Biology core", "18 of 28 credits", 64], ["Chemistry sequence", "8 of 16 credits", 50], ["General education", "26 of 32 credits", 81], ["Electives", "20 of 24 credits", 83]].map(([a,b,w]) => <div className="requirement" key={String(a)}><div><strong>{a}</strong><small>{b}</small></div><div className="mini-progress"><i style={{width:`${w}%`}}/></div></div>)}</Card><Card className="insight-card"><div className="insight-star">✦</div><p className="eyebrow">Pathly insight</p><h3>One choice could lighten senior year.</h3><p>Taking Organic Chemistry II next fall would leave more room for your capstone when it matters most.</p><Button variant="secondary">See suggested semester</Button></Card></div></main></> }

function Companion({ setPage }: { setPage: (p: Page) => void }) { const [message,setMessage]=useState(""); const [messages,setMessages]=useState<{who:string;text:string}[]>([{who:"Pathly",text:"You’ve got a lot on your plate today. Want to make a small plan for tonight?"}]); const send=()=>{if(!message.trim())return; setMessages(m=>[...m,{who:"You",text:message},{who:"Pathly",text:"I’d start with 45 minutes on your Biology Lab Report, then take a real break. If you still have energy, review the photosynthesis summary—nothing more is needed tonight."}]);setMessage("")}; return <><Topbar title="Your companion" onUpload={() => setPage("upload")}/><main className="page companion-page"><div className="companion-head"><div className="companion-orb">✦</div><div><h2>A little clarity, when you need it.</h2><p>Pathly is here to help you decide what matters—not ask you to do more.</p></div></div><Card className="chat-card"><div className="chat-log">{messages.map((m,i)=><div className={`message ${m.who === "You" ? "from-user" : "from-pathly"}`} key={i}><div className="message-label">{m.who}</div><p>{m.text}</p>{m.who === "Pathly" && i > 0 && <small>Based on: BIO 214 Lab Report · due today</small>}</div>)}</div><div className="suggestions"><button onClick={()=>setMessage("What should I study tonight?")}>What should I study tonight?</button><button onClick={()=>setMessage("Help me plan my week")}>Help me plan my week</button></div><div className="chat-input"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask Pathly anything…"/><button onClick={send} aria-label="Send message"><Icon name="send"/></button></div></Card></main></> }

function UploadPage({ setPage }: { setPage: (p: Page) => void }) { const [uploaded,setUploaded]=useState(false); return <><Topbar title="Upload center" onUpload={() => setUploaded(true)}/><main className="page"><div className="intro-row"><div><h2>Turn course materials into study support.</h2><p>Upload a lecture, syllabus, or reading. Pathly will organize the useful parts.</p></div></div><Card className="upload-zone"><div className="upload-graphic"><Icon name="upload" size={32}/></div><h3>Drop your material here</h3><p>PDF, PPTX, DOCX, or images up to 25 MB</p><Button onClick={() => setUploaded(true)}>Choose a file</Button></Card>{uploaded ? <Card className="upload-result"><div className="file-icon sage"><Icon name="file"/></div><div><Badge>Ready to study</Badge><h3>Photosynthesis — Lecture 8.pdf</h3><p>Pathly made a summary, 24 flashcards, key concepts, and a 10-question practice quiz.</p></div><Button onClick={() => setPage("study")}>Open materials <Icon name="arrow" size={16}/></Button></Card> : <div className="empty-materials"><Icon name="file" size={28}/><h3>No recent uploads</h3><p>Your course materials will live here when you’re ready.</p></div>}</main></> }

function Profile() { const [notices,setNotices]=useState(true); return <><Topbar title="Settings" onUpload={()=>{}}/><main className="page settings-page"><Card><div className="profile-heading"><div className="avatar large">AM</div><div><h2>Alex Morgan</h2><p>Biology · Class of 2027</p></div><Button variant="secondary">Edit profile</Button></div></Card><Card><p className="eyebrow">Notifications</p><h3>Helpful, not noisy.</h3><div className="setting-row"><div><strong>Gentle daily check-in</strong><p>A small prompt to help you choose your focus.</p></div><button className={`toggle ${notices?"on":""}`} onClick={()=>setNotices(!notices)} aria-label="Toggle daily check-in"><i/></button></div><div className="setting-row"><div><strong>Upcoming deadlines</strong><p>One reminder a day before important work is due.</p></div><button className="toggle on" aria-label="Toggle deadline reminders"><i/></button></div></Card><Card><p className="eyebrow">Privacy & storage</p><h3>Your materials are yours.</h3><div className="storage"><span>1.8 GB of 5 GB used</span><div className="mini-progress"><i style={{width:"36%"}}/></div></div><Button variant="secondary">Manage uploads</Button></Card></main></> }

function Landing({ enter }: { enter: () => void }) { return <div className="landing"><header className="landing-nav"><Logo/><div><button className="landing-link">About Pathly</button><Button onClick={enter}>Get started <Icon name="arrow" size={16}/></Button></div></header><main><section className="landing-hero"><Badge>For the full student life</Badge><h1>Because students carry<br/><em>more than deadlines.</em></h1><p>Pathly is your calm academic companion—helping you understand coursework, find your focus, and make space to breathe.</p><div className="hero-actions"><Button onClick={enter}>See your day <Icon name="arrow" size={16}/></Button><Button variant="secondary"><Icon name="play" size={16}/> Watch how it works</Button></div><div className="hero-preview"><div className="preview-copy"><p className="eyebrow">Tuesday, October 14</p><h3>Good morning, Alex.</h3><p>Let’s make today feel a little lighter.</p><div className="preview-task"><span>01</span><div><strong>Biology Lab Report</strong><small>Results + discussion · 90 min</small></div></div><div className="preview-task faint"><span>02</span><div><strong>Review Photosynthesis</strong><small>Cell Biology · 45 min</small></div></div></div><div className="preview-note"><span>✦</span><p>Everything else<br/>can wait.</p></div></div></section><section className="landing-features"><p className="eyebrow">A calmer way through college</p><h2>Built around what students actually need.</h2><div>{[["Understand", "Make dense course material easier to return to."], ["Organize", "See the few things that deserve your attention today."], ["Support", "Build a rhythm that considers your energy, too."]].map(([a,b])=><Card key={a}><span className="feature-star">✦</span><h3>{a}</h3><p>{b}</p></Card>)}</div></section></main></div> }

export default function App() { const [entered,setEntered]=useState(false); const [page,setPage]=useState<Page>("home"); const content=useMemo(()=>({home:<Dashboard setPage={setPage}/>,study:<StudyHub setPage={setPage}/>,calendar:<CalendarPage setPage={setPage}/>,degree:<DegreePage setPage={setPage}/>,companion:<Companion setPage={setPage}/>,upload:<UploadPage setPage={setPage}/>,profile:<Profile/>})[page],[page]); if(!entered)return <Landing enter={()=>setEntered(true)}/>; return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><div className="app-content">{content}</div><nav className="mobile-nav">{(["home","study","calendar","companion"] as Page[]).map(p=><button key={p} onClick={()=>setPage(p)} className={p===page?"active":""}><Icon name={p==="home"?"home":p==="study"?"book":p==="calendar"?"calendar":"sparkle"}/><span>{p==="home"?"Today":p==="study"?"Study":p==="calendar"?"Plan":"Ask"}</span></button>)}</nav></div>; }
