create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text not null default '', university text not null default '', major text not null default '', graduation_year integer check (graduation_year between 1900 and 2200), onboarding_completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
grant select, insert, update on public.profiles to authenticated;
revoke all on public.profiles from anon;
create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create function private.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.profiles (id,email,full_name) values (new.id,new.email,coalesce(new.raw_user_meta_data ->> 'full_name','')); return new; end; $$;
revoke all on function private.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
