import { useEffect, useState } from "react"
import { useSearchParams } from "react-router-dom"
import { Button } from "../ui/Button"
import { Card } from "../ui/Card"
import { disconnectGoogleCalendar, getGoogleCalendarConnection, loadGoogleCalendars, startGoogleCalendarConnection, syncGoogleCalendar, type GoogleCalendarChoice, type GoogleCalendarConnection } from "../../services/googleCalendar"
import { formatInstant } from "../../utils/dateTime"

export function GoogleCalendarConnectionCard({ timezone }: { timezone?: string | null }) {
  const [params, setParams] = useSearchParams(), [connection, setConnection] = useState<GoogleCalendarConnection | null>(null), [calendars, setCalendars] = useState<GoogleCalendarChoice[]>([]), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("")
  const refresh = async () => { const value = await getGoogleCalendarConnection(); setConnection(value); if (value?.status === "connected") setCalendars(await loadGoogleCalendars()) }
  useEffect(() => { void refresh().catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load Google Calendar.")) }, [])
  useEffect(() => { const result = params.get("google_calendar"); if (!result) return; setMessage(result === "connected" ? "Google Calendar connected. Choose calendars and sync availability." : "Google Calendar could not be connected."); params.delete("google_calendar"); setParams(params, { replace: true }) }, [params, setParams])
  const toggle = (id: string) => setCalendars(values => values.map(value => value.google_calendar_id === id ? { ...value, selected: !value.selected } : value))
  const connect = async () => { setBusy(true); setError(""); try { window.location.assign(await startGoogleCalendarConnection()) } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to connect Google Calendar."); setBusy(false) } }
  const sync = async () => { setBusy(true); setError(""); try { const result = await syncGoogleCalendar(calendars.filter(value => value.selected).map(value => value.google_calendar_id)); setMessage(`Availability synced (${result.busy_periods} busy period${result.busy_periods === 1 ? "" : "s"}).`); await refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to sync Google Calendar.") } finally { setBusy(false) } }
  const disconnect = async () => { if (!window.confirm("Disconnect Google Calendar and remove imported busy periods?")) return; setBusy(true); try { await disconnectGoogleCalendar(); setConnection(null); setCalendars([]); setMessage("Google Calendar disconnected.") } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to disconnect Google Calendar.") } finally { setBusy(false) } }
  const connected = connection?.status === "connected"
  return <Card className="connected-account-card"><div className="card-heading"><div><p className="eyebrow">Calendar connections</p><h3>Google Calendar</h3></div><span className={`badge ${connected ? "" : "badge-gray"}`}>{connected ? "Connected" : connection?.status === "needs_reauthorization" ? "Reconnect required" : "Not connected"}</span></div><p>Share only your busy times so Pathly can plan around work, appointments, and personal commitments. Event titles, descriptions, attendees, and meeting links are never imported.</p>{connected ? <><div className="canvas-connected-state"><div className="canvas-connection-details"><strong>{connection.google_account_email || "Google account"}</strong><small>{connection.last_synced_at ? `Last synced: ${formatInstant(connection.last_synced_at, timezone, { dateStyle: "medium", timeStyle: "short" })}` : "Last synced: Never"}</small></div></div><div className="canvas-token-panel"><p className="eyebrow">Calendars Pathly may use</p>{calendars.map(calendar => <label className="canvas-domain-field" key={calendar.id}><span><input type="checkbox" checked={calendar.selected} onChange={() => toggle(calendar.google_calendar_id)} disabled={busy}/> {calendar.display_name}</span>{calendar.time_zone && <small>{calendar.time_zone}</small>}</label>)}<div className="form-actions"><Button onClick={() => void sync()} disabled={busy || !calendars.some(value => value.selected)}>{busy ? "Syncing…" : "Sync availability"}</Button><Button variant="quiet" onClick={() => void disconnect()} disabled={busy}>Disconnect</Button></div></div></> : <Button onClick={() => void connect()} disabled={busy}>{busy ? "Connecting…" : connection?.status === "needs_reauthorization" ? "Reconnect Google Calendar" : "Connect Google Calendar"}</Button>}{message && <p className="save-success" role="status">{message}</p>}{(error || connection?.last_sync_error) && <p className="form-message" role="alert">{error || connection?.last_sync_error}</p>}</Card>
}
